name: Continuous Integration

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0

      - name: Install node modules
        run: npm ci

      # - name: Run linter
      #   run: npm run lint

      - name: Run tests
        run: npm run test:no-watch
  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0

      - name: Install node modules
        run: npm ci

      - name: Run linter
        run: npm run lint
  build:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0

      - name: Install node modules
        run: npm ci

      - name: Production Build
        run: npm run build
      - name: Upload build folder
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      # - name: Deploy build
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      #     BRANCH: gh-pages
      #     FOLDER: build
  build-and-deploy:
    name: Build & Deploy
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # - name: Setup Node.js for use with actions
        #   uses: actions/setup-node@v1.1.0
        # - name: Install node modules
        #   run: npm ci
        # - name: Production Build
        # run: npm run build
      - name: Download build folder
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Deploy build
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
